theme = "aws-community-day"
baseURL = "https://awsbaltic.eu/"
languageCode = "en-us"
title = "AWS Community Day Baltic"
canonifyURLs = true
buildFuture = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
ignoreLogs = ['warning-goldmark-raw-html']
[menu]
  [[menu.main]]
    name = "Speakers"
    url = "/speakers/"
    weight = 30
  [[menu.main]]
    name = "Edycja 2025"
    url = "https://awsbaltic.eu/2025/"
    weight = 800
[params]
headerLogo = "/img/awsbaltic.png"
images = ["/img/awsbaltic.png"]
ogImage = "/img/awsbaltic.png"
twitterImage = "/img/awsbaltic.png"
twitterCard = "summary_large_image"